### ISSUE TITLE
Is it possible to change the port number and format?

### ISSUE THREAD

**Issue by szjiajin** [siddhi-io/siddhi-io-tcp#38]
**Description:**

In my application I need to receive data from tcp connection. I had some questions when I was testing this extension.

1. The port number seems to be fixed. Is there any way to change it without modifying the source code?
2. There might be some self-defined protocol in tcp message. Is it possible to define the format ourselves? (like writing a custom map extension)
3. The data source only sends data by responding a transmission request. Is it possible to make the source actively request for data (by sending tcp message)?
Thank you in advance!

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**
2.0.17
**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by niveathika** [comment]
@szjiajin,

Please find my answers below,
1. Port number can be overwritten as a system parameter if you are using SP please see the following [doc](https://docs.wso2.com/display/SP420/Configuring+System+Parameters+for+Siddhi+Extensions) on the setting system parameter. else you can set it using inMemoryConfig provider.
2. Yes, you can write a custom map extension and use it with TCP.
3. As of now, this is not possible.

Best Regards,
Niveathika

**Comment by niveathika** [comment]
Closing this as it is answered
