### ISSUE TITLE
Java 7 version

### ISSUE THREAD

**Issue by felwolff** [siddhi-io/siddhi-io-tcp#44]
Since Siddhi v3 is compiled with Java 7, I was wondering whether there is a Java 7 version of the TCP extension available?

**Comment by niveathika** [comment]
@felwolff. A bit of clarification on your request is needed? Are you checking for the latest version of siddhi-io-tcp, [v 2.0.22](https://github.com/wso2-extensions/siddhi-io-tcp/releases/tag/v2.0.20) that is compiled in Java 7 or the v1.x version of the tcp extension compatible with Siddhi 3?

**Comment by mohanvive** [comment]
There is no any siddhi-io-tcp extension that is compatible with Siddhi 3.x version. If you are looking for an TCP extension (for Siddhi 3.x.x) then you have to implement a custom one.
